apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Not used for ASM 1.9
# resources:
#   - ../../../templates/virtualservice--in-eks-for-gke.yaml

commonAnnotations:
  configmanagement.gke.io/cluster-selector: eks-prod-us-west2ab-1

commonLabels:
  provider: aws
  cluster: eks-prod-us-west2ab-1