apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Not used for ASM 1.9
  # - ../../../templates/serviceentry--gke-internal-dns.yaml
  # - ../../../templates/serviceentry--in-gke-for-eks-global.yaml
  # - ../../../templates/service--gke-crdb.yaml

commonAnnotations:
  configmanagement.gke.io/cluster-selector: gke-prod-us-west2a-1

commonLabels:
  provider: gcp
  cluster: gke-prod-us-west2a-1